기본적으로 알기
- 여러 가지 문자열 치환 / re.compile(azAZ) 확인
- 데이터 정보 / 역순으로 정렬 / 특정 열의 항목 포함되는 것 찾기 (=, <, >) / 여러 기준으로 정렬 / 상위 n개, & and | or
- 최대 / 최소 / 중복 제거
- group by 
- isnull, fillna

help(), dir() 활용하기 

-평균값 (가장 큰값 10개는 10번째 값으로 대체, 특정 컬럼에서 00보다 큰 값의 평균)
-표준편차 (결측치가 있을 때 표준편차, 결측치를 채운 후 표준편차 80% 데잉터 중앙값으로 채움)
-이상치들의 합
-이상치 처리 (분류)

kmeans??


분류 vs 회귀(예측)
타이타닉, 손글씨 / 분류 : DecisionTreeClassifier, RandomForestClassifier, SVC - StandardScaler()
    숫자의 차이가 모델에 영향을 주지 않는 트리 계열 모델
아이리스, 유방암, 집값, 와인 품질 / 회귀 : DecisionTreeRegressor, RandomForestRegressor, LogisticRegression, KNeighborsClassifier  SVR - MinMaxScaler()
    숫자의 차이가 모델에 영향을 미치는 선형 계열 모델 (주로 원핫인코딩)
    특성별로 데이터 스케일이 다르면, 특정 요소가 예측에 영향을 주지 않음. (스케일러 사용이유)

라벨 인코딩 vs 원핫인코딩
라벨 - 문자형을 정수형으로 인코딩 / 가중치의 차이가 생긴다. 트리 기반 알고리즘에서 사용 / 범주형 (성별, 과목, 성적)
원핫 - 숫자의 크고 작은 특성을 없애기 위함 / 모든 문자열 값이 숫자형이어야 함, 2차원데이터가 필요함 / 선형
LabelEncoder() + OneHotEncoder() = get_dummies()

0. 분류, 회귀 구분
1. 데이터 파악 :info() 확인, nan값 처리, 중복 제거, 시각화, 아웃라이어
2. 인코딩( get_dummies() ), test_train (교차검증시)
3. scaler
4. model
5. predict

seaborn 그리기
plt.boxplot(df.age)
sns.catplot(kind='box',data=df, x='grade',y='price')
sns.violinplot(data=df, x='Species', y='SepalLengthCm') => catplot + kdeplot
sns.heatmap(df.corr(), annot=True, fmt='.2f')

null 값처리
df.isnull().sum()
평균으로 : df.age = df.age.fillna(df.age.mean())
특정값 평균으로  : df.Age = df.Age.fillna(df.groupby('Name')['Age'].mean())
많은 값 : df.cabin.value_counts()
replace : 

feature 묶기(더하기, age 별로) / 삭제
중복 제거 : df.duplicated().sum()
drop : train = df.drop( [‘name’,‘age’,‘parch’ ], axis=1)
def category_age(x):
    if x < 10:
        return 0
    elif x < 20:
        return 1
    elif x < 30:
        return 2
    elif x < 40:
        return 3
    elif x < 50:
        return 4
    elif x < 60:
        return 5
    elif x < 70:
        return 6
    else:
        return 7    
    
train['Age_cat'] = train['Age'].apply(category_age)

문자를 숫자로 (원핫 인코딩*)
map : df.cabin = df.cabin.map({ ‘a’ : 0 , ‘b’ : 1, ‘c’ : 2 })

특정값 추출 
data[(data.Age>30) & (data.Survived==1)].groupby('Sex').count()
df.loc [ df["points"] > 3, "penalty"] = 0 
     points칼럼이 3보다 큰 행들을 뽑아내서 , penalty칼럼에 0을 대입

싸이킷런
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

x_train, x_test, y_train, y_test = train_test_split(train_data, target_data, test_size = 0.3, stratify=target_data)

tree = DecisionTreeClassifier()
tree.fit(x_train,y_train)
tree.score(x_test, y_test)

forest = RandomForestClassifier(n_estimators=10)
forest.fit(x_train, y_train)

print('training set accuracy:', forest.score(x_train, y_train))
print('test set accuracy:', forest.score(x_test, y_test))

prediction_by_forest = forest.predict(x_test)


====================================================
예측 : Feature Scaling은 특징 값의 범위를 균일하게 맞춰주는 작업입니다.

from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(train, target, test_size=0.3)

scaler = StandardScaler()
scaler.fit(X_train) #fit_trasform() : fit() + transform()
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

forest = RandomForestClassifier(n_estimators=10)
forest.fit(X_train,y_train)  
y_pred = forest.predict(X_test)
print('Accuracy is:',forest.score(X_test,y_test))


from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_train)  #train꺼로 transform한걸로 fit 중요!!!!
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변화값: ', labels)
# 인코딩 변화값:  [0 1 4 5 3 3 2 2]
# 회귀 알고리즘에는 적용하면 안됨, 트리 계열의 알고리즘은 숫자의 이런 특성을 반영하지 않으므로 레이블 인코딩도 별 문제가 없음

from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전기레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1,1)

# 원-핫 인코딩을 적용
oh_encoder = OneHotEncoder(categories='auto')
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
# 원-핫 인코딩 데이터
# [[1. 0. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 1. 0.]
#  [0. 0. 0. 0. 0. 1.]
#  [0. 0. 0. 1. 0. 0.]
#  [0. 0. 0. 1. 0. 0.]
#  [0. 0. 1. 0. 0. 0.]
#  [0. 0. 1. 0. 0. 0.]]


# get_dummies() : 판다스에서 이용할 수 있는 원핫 인코딩 API
# 사이킷런의 OneHotEncoder와는 달리 문자열 카테고리 값을 숫자형으로 변환할 필요 없이 바로 변환됨
df = pd.DataFrame({'item' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)


In [2]:
#대체
import pandas as pd
data = pd.DataFrame([0, 1, 0, 1, 0])
data = data.replace(0, 2)
data

0
0  2
1  1
2  2
3  1
4  2

In [ ]:
#정렬
df = df.sort_values('f5', ascending=False) #컬럼 기준 내림차순
df = df.sort_values(['f5','f6'], ascending=False) #여러 컬럼 오름차순, 내림차순 ascendig=[False, True] 가능
df = df.sort_index() #인덱스 기준 올림차순

In [ ]:
#표준편차
np.std(df.col1)

#평균값
df.col1.mean()

#중간값
df.col1.median()

#절대값
np.abs()

In [ ]:
#결측치 
df.isnull().sum() #확인
df.col1.fillna('특정값') #채우기
df.dropna() #결측치 포함된거 다 지움
df.dropna(axis=0)
df.dropna(how='any') #결측치 있는 행 다 지워짐
df.dropna(axis=1) #결측치 있는 열 다 지워짐

df = df.dropna(subset=['col1']) #특정 열 결측치 제거 
df = df.dropna(how='any',subset=['col1','col2']) #특정 열 둘 중 하나 결측치 있을 때 / 모두 결측치 있을 때 how ='all'


#drop
df.drop(['idx1','idx2']) #행 
df.drop(['col1','col2'],axis=1)


In [ ]:
#groupby
df_sum = df.groupby(['col1','col2']).sum()

In [ ]:
#분류를 위해서 나눔
def category_age(x):
    if x < 10:
        return 0
    elif x < 20:
        return 1
    elif x < 30:
        return 2
    elif x < 40:
        return 3
    elif x < 50:
        return 4
    elif x < 60:
        return 5
    elif x < 70:
        return 6
    else:
        return 7    
    
train['Age_cat'] = train['Age'].apply(category_age)
test['Age_cat'] = test['Age'].apply(category_age)

In [ ]:
#매핑 / 데이터 수치화
train['Embarked'] = train['Embarked'].map({'C': 0, 'Q': 1, 'S': 2})
test['Embarked'] = test['Embarked'].map({'C': 0, 'Q': 1, 'S': 2})

#or
train['Sex'].replace({'male':0, 'female':1}, inplace=True)


#원핫인코딩
train = pd.get_dummies(train, columns=['Initial'], prefix='Initial')
test = pd.get_dummies(test, columns=['Initial'], prefix='Initial')

#이후에 중복 feature 삭제
train.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin'], axis=1, inplace=True)
test.drop(['PassengerId', 'Name',  'SibSp', 'Parch', 'Ticket', 'Cabin'], axis=1, inplace=True)


In [1]:
#help, dir
import pandas as pd
import numpy as np

df = pd.read_csv('basic1.csv') 
# df = df.drop('f4')

print(dir(df))
print(help(df.drop))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul